---
- name: start of play9 all tasks togeather
  hosts: weball
  tasks:
  - name: add group deploy
    group:
      name: deploy

  - name: add user user-deploy
    user: name=deploy-user group=deploy shell=/bin/bash

  - name: install httpd
    yum: name=httpd state=present
    
  - name: start service httpd
    service: name=httpd state=started

  - name: create file “index.html” in /var/www/html
    file: path=/var/www/html/index.html state=directory

  - name: install git
    yum: name=git state=present

  - name: install wget
    yum: name=wget state=present

  - name: clone git
    git: dest=. repo=https://github.com/scmgalaxy/ansible-role-template


...
