- name: Start the Play

  hosts: weball
  vars:

     dir: etc
  tasks:
   
  - name: install the latest version of Apache

    yum:

      name: httpd

      state: present

    when: ansible_os_family == "RedHat"



  - name: Install apache httpd  (state=present is optional)

    apt:

      name: apache2

      state: present   

      update_cache: yes

    when: ansible_os_family == "Debian"

  - name: Recursively find /etc files
    find:
      paths: /etc
      register: find_output


  - debug:

      msg: This is a directory {{ find_output }}

