- name: Start the Play

  hosts: weball

  tasks:

  - name: install the latest version of Apache

    yum:

      name: httpd

      state: present

    when: ansible_os_family == "RedHat"



  - name: Install apache httpd  (state=present is optional)

    apt:

      name: apache2

      state: present   

      update_cache: yes

    when: ansible_os_family == "Debian"



  - name: Install common software requirements

    apt: pkg={{ item }} state=present

    with_items:

       - git

       - htop

       - vim

    when: ansible_os_family == "Debian"
