- name: Start the Play

  hosts: weball

  vars:

    myname: rajutemp



  tasks:

  - name: install the latest version of Apache

    yum:

      name: httpd

      state: present

    when: ansible_os_family == "RedHat"

  - name: Install apache httpd  (state=present is optional)

    apt:

      name: apache2

      state: present   

      update_cache: yes

    when: ansible_os_family == "Debian"

  - name: Copy file with owner and permissions

    copy:

      src: index.html

      dest: /var/www/html/

  - name: Start service httpd, if not started

    service:

      name: httpd

      state: started

  - name: Run a script with arguments (using 'cmd' parameter)

    script:

      cmd: deploy.sh
