- name: Create a playbook where you should install a webserver into 2 OS type(Ubuntu and RHEL) with fact conditioning. and list out a directory which in “/etc” and display such as “This is a directory /file in /etc:-XXXx”
#To be used Conditiong, looping, regiter and fact variable
  hosts: ExcercisePart3
  tasks:
  - name: install the latest version of Apache
    yum:
      name: httpd
      state: present
    when: ansible_os_family == "RedHat"

  - name: Install apache httpd  (state=present is optional)
    apt:
      name: apache2
      state: present   
      update_cache: yes
    when: ansible_os_family == "Debian"

  - name: list out directory
    find: 
        paths: /var/log
        recurse: no
        file_type: directory
    register: files

  - debug:
      msg: This is a directory {{files}} in /etc
...
