---
- name: Write a Ansible Playbook to create a file called “index.html” in /var/www/html with some dummy html contents.
  hosts: web1
  tasks:
  - name: Copy index file to httpd path
    lineinfile:  create=yes path=/var/www/html/index.html line='This is from my play book by Agasthi'
...
