- name: Assignment1
  hosts: weball
  tasks:
  - name: install the latest version of Apache
    yum:
      name: httpd
      state: present
    when: ansible_os_family == "RedHat"

  - name: Install apache httpd  (state=present is optional)
    apt:
      name: apache2
      state: present   
      update_cache: yes
    when: ansible_os_family == "Debian"
  - name: Find folder
    find:
      paths: /etc/
      recurse: no
    register: folders_found
  - name: Loop
    debug:
      msg: "{{ folders_found.files| map(attribute='path') | list }}"
