- name: Start the Play
  hosts: weball
  tasks:
  - name: install the latest version of Apache
    yum:
      name: httpd
      state: present
    when: ansible_os_family == "RedHat"
        
  - name: Recursively find /tmp files older than 2 days
    find:
      paths: /var/www/html/
      recurse: yes
      pattern: "*.html"
    register: files
  - debug:
      msg: Files are "{{ files }}"



  - name: Install apache httpd  (state=present is optional)
    apt:
      name: apache2
      state: present
      update_cache: yes
    when: ansible_os_family == "Debian"
