---
- name: Start the Play
  hosts: web1
  tasks:
    - name: Creating group name deploy
      group:
        name: deploy
    - name: creating deploy-user
      user: 
        name: deploy-user
        group: deploy 
        shell: /bin/bash
    - name: Installing httpd
      yum:
        name: httpd
        state: installed
    - name: starting httpd
      service:
        name: httpd
        state: started
    - name: Creating index.html file
      lineinfile:
        create: yes 
        path: /var/www/html/index.html
        line: it is index
    - name: Installing git and wget
      yum:
        name: git,wget
        state: installed
    - name: Cloning from git
      git:
        clone: yes
        dest: /root/OnMob-Docker-Ansible-July-2020/koyel
        repo: https://github.com/scmgalaxy/ansible-role-template
