:--
# tasks file for web

  - name: install the latest version of Apache
    yum:
      name: httpd
      state: present
    when: ansible_os_family == "RedHat"

  - name: Run a script with arguments (using 'cmd' parameter)
    script:
      cmd: deploy.sh

  - name: Copy file with owner and permissions
    copy:
      src: index.html
      dest: /var/www/html/

  - name: Create a directory if it does not exist
    file:
      path: /var/www/html/{{ dir }}
      state: directory
      mode: '0755'

  - name: Template a file to /etc/files.conf
    template:
      src: index.html.j2
      dest: /var/www/html/{{ dir }}/index.html

  - name: Template a file to /etc/files.conf
    template:
      src: httpd.conf.j2
      dest: /etc/httpd/conf/httpd.conf
    notify: restart service
      
  - name: Start service httpd, if not started
    service:
      name: httpd
      state: started
