- name: Play for cloning a git repo          
  hosts: web
  tasks:
  - name: clone a repo
    git:
      clone: yes
      repo: https://github.com/scmgalaxy/ansible-role-template
      dest: /opt/clonedrepo
