---
- name: Start the Play
  hosts: weball
  vars:
    myname: rajutemp

  tasks:
  - name: install the latest version of Apache
    yum:
      name: httpd
      state: present
    when: ansible_os_family == "RedHat"
	
  - name: Install apache httpd  (state=present is optional)
    apt:
      name: apache2
      state: present   
    when: ansible_os_family == "Debian"
	
  - name: find paths  (state=present is optional)
    command: "find /etc *”
	register: path_result   
	when: ansible_os_family == "Debian"
	
  - name: find paths  (state=present is optional)
    shell: "find /etc *”
	register: path_result   
	when: ansible_os_family == "Debian"
	  
  - name: Template a file to /etc/files.conf
    template:
      src: index.html.j2
      dest: /var/www/html/index.html
	with_items: path_result
	notify: restart service1
	when: ansible_os_family == "RedHat"
	
  - name: Template a file to /etc/files.conf
    template:
      src: index.html.j2
      dest: /var/www/html/index.html
	with_items: path_result
	notify: restart service2
	when: ansible_os_family == "Debian"
	
  - name: Start service httpd, if not started
    service:
      name: httpd
      state: started

  handlers:
  - name: restart service1
    service:
      name: httpd
      state: restarted
	  
  - name: restart service2
    service:
      name: apache2
      state: restarted
