
---
- name: Playbook 8          
  hosts: all
  tasks:
  - clone: git repo. thttps://github.com/scmgalaxy/ansible-role-template
    git:
      clone:yes 
      repo:https://github.com/scmgalaxy/ansible-role-template dest=/opt/git
...

